name = "BaseModelica"
uuid = "a17d5099-185d-4ff5-b5d3-51aa4569e56d"
authors = ["jClugstor <jadonclugston@gmail.com> and contributors"]
version = "1.0.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
Aqua = "0.8"
Automa = "1"
ModelingToolkit = "8.75, 9"
SafeTestsets = "0.1"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "SafeTestsets", "Test"]
